### ISSUE TITLE
Oboji notifikace 

### ISSUE THREAD

**Issue by kvetak** [nesfit/kryptoalarm#12]
Umoznit v ramci Notifier.py, aby poslal jak email, tak udelal API spojeni. Use-case je takovy, ze v pripade vyskytu adresy chci, aby skript za me poslal email a zaroven naplnil databazovou tabulku Notifications patricnymi daty.

**Comment by kvetak** [comment]
Ja to myslel tak, že se přidá třetí možnost Rest+Email,ze zdrojaku mi prijde,ze to teď dělá obojí dohromady bez možnosti specifikovat.

**Comment by vokracko** [comment]
Pochopil jsem to tak že se bude vždy posílat obojí, opravím

**Comment by kvetak** [comment]
Jen co to bude zpet, tak se z toho ja pokusim udelat ten docker kontejner.
