### ISSUE TITLE
systemd service

### ISSUE THREAD

**Issue by vokracko** [nesfit/kryptoalarm#3]

**Comment by kvetak** [comment]
Misto systemd sluzby navrhuji z Pythoni casti udelat docker container, ktery bude mit perzistentne dostupny soubor config.py

**Comment by kvetak** [comment]
Viz napr. https://runnable.com/docker/python/dockerize-your-python-application

**Comment by kvetak** [comment]
via  https://github.com/nesfit/kryptoalarm/commit/ba20bc0fdf497f902350dda3be1efc4ddec1760d
