### ISSUE TITLE
inout email notification duplicity

### ISSUE THREAD

**Issue by vokracko** [nesfit/kryptoalarm#9]

**Comment by kvetak** [comment]
Ve front-endu snadno v ramci RESToveho volani, ala:
```
        foreach($data['transactions'] as $t) {
            if (!(Notification::where('tx_hash','=',$t)
                ->where('watchlist_id','=',$watchlist->id)->get()->isEmpty())
            ) { continue; }
```

Na toto je vhodne vybudovat taky DB index pro policko tx_hash.

Ocekaval bych, ze se v DB budou objevovat 2 (jeden za vstup a jeden za vystup transakce) misto 1 zaznamu. Nicmene pri dlouhodobem provozu monitoru dochazi k podstatne vetsimu duplikovani (1 transakce se objevuje klidne 4× a vice).
